[package]
name = "PSP-RUST"
version = "0.1.0"
authors = ["sanyabeast <a.gvrnsk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psp = "0.1.2"